# Based on https://github.com/lupyuen/pinetime-lab/blob/master/doc/buildAndProgram.md
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.18.0
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        # GNU Embedded Toolchain for Arm release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")
        release: 8-2019-q3
        # Directory to unpack GCC to. Defaults to a temporary directory.
        directory: arm-none-eabi
    - uses: actions/checkout@v2
    - name: Show Files
      run:  set ; pwd ; ls -l
    - name: mkdir build
      run:  mkdir build
    - name: cd build
      run:  cd build
    - name: cmake
      run:  cmake -DARM_NONE_EABI_TOOLCHAIN_PATH=../arm-none-eabi -DNRF5_SDK_PATH=../nrf5_sdk -DUSE_OPENOCD=1 ../
    - name: make
      run:  make -j pinetime-app
      
