# Moved to https://github.com/lupyuen/pinetime-lab/blob/master/.github/workflows/main.yml

on:
  schedule:
    # Runs at midnight 1 Jan every year
    - cron:  '*/88 */88 */88 */88 *'
    
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - run: echo Happy New Year!
